apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webapp-service-account-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: microservices-kubernetes-namespace-reader
subjects:
- kind: ServiceAccount
  name: webapp-service-account
  namespace: default
