apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: gateway-config
spec:
  healthCheck:
    timeoutSec: 100
    checkIntervalSec: 120
    type: HTTP
    requestPath: /actuator/health
    port: 9090