apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: webapp-service-account
      nodeSelector:
        kubernetes.io/arch: arm64
        cloud.google.com/compute-class: Scale-Out
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: gateway-app-container
        image: dhairya22/shareitinerary:gateway-latest    
        ports:
        - containerPort: 9090 # where the pod of postgres is running
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9090
          initialDelaySeconds: 120
          periodSeconds: 100
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  annotations:
    cloud.google.com/backend-config: '{"ports": {"9090":"gateway-config"}}'
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 9090   # port address where service is running
      targetPort: 9090 # to transfer the incoming request to the port
